(G-CODE GENERATED BY FLATCAM v8.992 - www.flatcam.org - Version Date: 2020/05/03)

(Name: mosfetSwitches-PTH.drl_cnc)
(Type: G-code from Excellon)
(Units: MM)

(Created on Sunday, 29 June 2025 at 14:18)

(This preprocessor is the default preprocessor used by FlatCAM.)
(It is made to work with MACH3 compatible motion controllers.)


(TOOLS DIAMETER: )
(Tool: 1 -> Dia: 1.0007599999999999)

(FEEDRATE Z: )
(Tool: 1 -> Feedrate: 300.0)

(FEEDRATE RAPIDS: )
(Tool: 1 -> Feedrate Rapids: 1500)

(Z_CUT: )
(Tool: 1 -> Z_Cut: -1.0)

(Tools Offset: )
(Tool: 1 -> Offset Z: -0.0)

(Z_MOVE: )
(Tool: 1 -> Z_Move: 2)

(Z Toolchange: 25.0 mm)
(X,Y Toolchange: 0.0000, 0.0000 mm)
(Z Start: None mm)
(Z End: 2.0 mm)
(Steps per circle: 64)
(Preprocessor Excellon: default)

(X range:    2.3876 ...    3.3884  mm)
(Y range:    4.6558 ...   15.8166  mm)

(Spindle Speed: 10000.0 RPM)
G21
G90
G94



G01 F300.00

M5
G00 Z25.0000
T1
G00 X0.0000 Y0.0000                
M6
(MSG, Change to Tool Dia = 1.0008 ||| Total drills for tool T1 = 5)
M0
G00 Z25.0000

M03 S10000
G4 P1.0
G00 X2.8880 Y15.3162
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G00 X2.8880 Y12.7762
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G00 X2.8880 Y10.2362
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G00 X2.8880 Y7.6962
G01 Z-1.0000
G01 Z0
G00 Z2.0000
G00 X2.8880 Y5.1562
G01 Z-1.0000
G01 Z0
G00 Z2.0000
M05
G00 Z2.00

